-- SQL Script untuk membuat tabel logging Pentaho
-- Jalankan script ini di database yang digunakan untuk DW_Connection
-- Ini opsional, hanya diperlukan jika ingin menggunakan fitur logging

-- Tabel untuk logging transformation
CREATE TABLE IF NOT EXISTS log_trans (
    ID_BATCH INT,
    CHANNEL_ID VARCHAR(255),
    TRANSNAME VARCHAR(255),
    STATUS VARCHAR(15),
    LINES_READ BIGINT,
    LINES_WRITTEN BIGINT,
    LINES_UPDATED BIGINT,
    LINES_INPUT BIGINT,
    LINES_OUTPUT BIGINT,
    LINES_REJECTED BIGINT,
    ERRORS BIGINT,
    STARTDATE DATETIME,
    ENDDATE DATETIME,
    LOGDATE DATETIME,
    DEPDATE DATETIME,
    REPLAYDATE DATETIME,
    LOG_FIELD TEXT,
    EXECUTING_SERVER VARCHAR(255),
    EXECUTING_USER VARCHAR(255),
    CLIENT VARCHAR(255),
    PRIMARY KEY (ID_BATCH, CHANNEL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabel untuk performance logging
CREATE TABLE IF NOT EXISTS perf_log (
    ID_BATCH INT,
    SEQ_NR INT,
    LOGDATE DATETIME,
    TRANSNAME VARCHAR(255),
    STEPNAME VARCHAR(255),
    STEP_COPY INT,
    LINES_READ BIGINT,
    LINES_WRITTEN BIGINT,
    LINES_UPDATED BIGINT,
    LINES_INPUT BIGINT,
    LINES_OUTPUT BIGINT,
    LINES_REJECTED BIGINT,
    ERRORS BIGINT,
    INPUT_BUFFER_ROWS BIGINT,
    OUTPUT_BUFFER_ROWS BIGINT,
    PRIMARY KEY (ID_BATCH, SEQ_NR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabel untuk channel logging
CREATE TABLE IF NOT EXISTS channel_log (
    ID_BATCH INT,
    CHANNEL_ID VARCHAR(255),
    LOG_DATE DATETIME,
    LOGGING_OBJECT_TYPE VARCHAR(255),
    OBJECT_NAME VARCHAR(255),
    OBJECT_COPY VARCHAR(255),
    REPOSITORY_DIRECTORY VARCHAR(255),
    FILENAME VARCHAR(255),
    OBJECT_ID VARCHAR(255),
    OBJECT_REVISION VARCHAR(255),
    PARENT_CHANNEL_ID VARCHAR(255),
    ROOT_CHANNEL_ID VARCHAR(255),
    PRIMARY KEY (ID_BATCH, CHANNEL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabel untuk step logging
CREATE TABLE IF NOT EXISTS step_log (
    ID_BATCH INT,
    CHANNEL_ID VARCHAR(255),
    LOG_DATE DATETIME,
    TRANSNAME VARCHAR(255),
    STEPNAME VARCHAR(255),
    STEP_COPY INT,
    LINES_READ BIGINT,
    LINES_WRITTEN BIGINT,
    LINES_UPDATED BIGINT,
    LINES_INPUT BIGINT,
    LINES_OUTPUT BIGINT,
    LINES_REJECTED BIGINT,
    ERRORS BIGINT,
    LOG_FIELD TEXT,
    PRIMARY KEY (ID_BATCH, CHANNEL_ID, STEPNAME, STEP_COPY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabel untuk metrics logging
CREATE TABLE IF NOT EXISTS metrics_log (
    ID_BATCH INT,
    CHANNEL_ID VARCHAR(255),
    LOG_DATE DATETIME,
    METRICS_DATE DATETIME,
    METRICS_CODE VARCHAR(255),
    METRICS_DESCRIPTION VARCHAR(255),
    METRICS_SUBJECT VARCHAR(255),
    METRICS_TYPE VARCHAR(255),
    METRICS_VALUE BIGINT,
    PRIMARY KEY (ID_BATCH, CHANNEL_ID, METRICS_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Index untuk performa query
CREATE INDEX idx_log_trans_transname ON log_trans(TRANSNAME);
CREATE INDEX idx_log_trans_logdate ON log_trans(LOGDATE);
CREATE INDEX idx_perf_log_transname ON perf_log(TRANSNAME);
CREATE INDEX idx_perf_log_logdate ON perf_log(LOGDATE);

